name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses:
        actions/checkout@v3

        # 安装 Node 环境
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Install and Build
      run: npm install

    - name: Run Build Script
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
      folder: docs/.vitepress/dist
      branch: gh-pages
